name: '@andyschwartz'
favicon: null
layout_spectrum: 0.26219
typography_spectrum: 0.22171
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#000000'
    - '#1f1410'
    - '#3f2b24'
    - '#514b4d'
    - '#7f7e83'
  brandStrength: 1
  lightness: 0.7026905308011919
  saturation: 0.21963709639385343
  rhythmicContrast: 0.5864682120736688
purpose: []
