name: '@andyschwartz'
favicon: null
layout_spectrum: 0.3484120510984212
typography_spectrum: 0.4796364747453481
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#B8B42D'
    - '#697A21'
    - '#FFFCE8'
    - '#3E363F'
    - '#DD403A'
  brandStrength: 0.36730184382759035
  lightness: 0.7026905308011919
  saturation: 0.21963709639385343
  rhythmicContrast: 0.5864682120736688
purpose: []
